language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
before_install: sudo apt-get update
# command to install dependencies
install:
  - sudo make sysdeps
  - make install
# command to run tests
script: py.test -q --tb native -s tests
